name: hello-world
'on': push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello 403 Awesome World!"
  my-job2:
    runs-on: ubuntu-latest
    steps:
      - name: my-step2
        run: echo "Hello Super World!"
